### ISSUE TITLE
Changes to coverage tests result in SonarCloud error

### ISSUE THREAD

**Issue by semenko** [statisticsnorway/ssb-pypitemplate#48]
Hi! In your latest release #47 , I believe the coverage test code changes in #44 are breaking SonarCloud

Here's an example build:
https://github.com/mcwdsi/bam2tensor/actions/runs/7576080680/job/20634120056

This results in a SonarCloud error here, and no reported coverage:
https://sonarcloud.io/summary/new_code?id=mcwdsi_bam2tensor&branch=main

SonarCloud reports this error
```
The following error(s) occurred while trying to import coverage report:
Cannot resolve 4 file paths, ignoring coverage measures for those files%nCannot resolve the file path 'src/bam2tensor/__init__.py' of the coverage report, the file does not exist in all 'source'.
```
![image](https://github.com/statisticsnorway/ssb-pypitemplate/assets/167135/6619d773-5243-4946-a04e-471520b17f21)

I suspect this might be due to changes in the pattern matching of `sed` though I'm not very familiar with what SonarCloud expects:

![image](https://github.com/statisticsnorway/ssb-pypitemplate/assets/167135/1008d5b5-4aa0-4d29-8723-f8944acf8cfb)

**Comment by arneso-ssb** [comment]
@semenko Thanks for the report. I have reproduced the issue, and the reason is the change to use relative paths when running coverage. The SonarCloud fix for coverage paths needs to be updated.

As workaround you can remove the following line under the `[tool.coverage.run]` section in `pyproject.toml`:
`relative_files = true`.

I want it to work with relative paths, since that solves a problem combining coverage-files from different platforms using different paths. I will look into it later this week.
